/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StarWarsCharacters {
        "characterId"?: string;
    }
}
declare global {
    interface HTMLStarWarsCharactersElement extends Components.StarWarsCharacters, HTMLStencilElement {
    }
    var HTMLStarWarsCharactersElement: {
        prototype: HTMLStarWarsCharactersElement;
        new (): HTMLStarWarsCharactersElement;
    };
    interface HTMLElementTagNameMap {
        "star-wars-characters": HTMLStarWarsCharactersElement;
    }
}
declare namespace LocalJSX {
    interface StarWarsCharacters {
        "characterId"?: string;
    }
    interface IntrinsicElements {
        "star-wars-characters": StarWarsCharacters;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "star-wars-characters": LocalJSX.StarWarsCharacters & JSXBase.HTMLAttributes<HTMLStarWarsCharactersElement>;
        }
    }
}
